### ISSUE TITLE
msub_args in default_test_config.yaml does not do anything

### ISSUE THREAD

**Issue by cadejager** [lanl/Pavilion#26]
The option msub_args in default_test_config.yaml does not seem to be implemented.

**Comment by ironbars** [comment]
Hi there, any update on this issue?  I checked out the repo a few weeks ago I'm having the same trouble with msub_args.

**Comment by cadejager** [comment]
If you checkout the testing branch it has been fixed. I intend to merge that branch as is into master this week as my tests have all been successful and I have not come across any reason to believe that it is not stable.

**Comment by ironbars** [comment]
Ah, that explains it then.  I checked out master.  Thank you.

**Comment by cadejager** [comment]
This fix is now in master.
